### PR TITLE
Update to nodejs 8 and npm 5

### PR DESCRIPTION
**Pull request by Page-**

### CODE REVIEW

**Comment by lurch** [comment]
Dunno if this is a helpful comment or not, but @jhermsmeier recently had problems when trying to upgrade Etcher to NPM v5 https://github.com/resin-io/etcher/pull/1475

**Comment by emirotin** [comment]
npm5 is claimed to be much faster to install big trees
node8 also claims v8 perf improvements

**Comment by Page-** [comment]
Nodejs 8 is now LTS: https://medium.com/the-node-js-collection/news-node-js-8-moves-into-long-term-support-and-node-js-9-becomes-the-new-current-release-line-74cf754a10a0

**Comment by dfunckt** [comment]
Would be very interesting to see a proper chhangelog that isn’t at blog post or commit level that details breaking changes, if any. I couldn’t find one — anyone knows?

**Pull request merged**
